### ISSUE TITLE
Ubuntu 22.04 new libssl

### ISSUE THREAD

**Issue by dalamanster** [jeff89179/securecrt-ubuntu-unsupported#1]
Hi,

please update libssl to new version 1.3 (currently you recommend 1.2 but that was remove from server)

libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
-->
libssl1.1_1.1.1l-1ubuntu1.3_amd64.deb

I tested this on ubuntu 22.04 - Securecrt 9.2.1

**Comment by jeffest-jeff** [comment]
Done, thanks for the heads up!
